Enviromental Aids Merge
devTrivedi1/MajorProject pull request #124
Opened 2024-03-20 11:02 UTC by somnolentz

closes #105 
closes #104 
closes #103 

added prefabs for all the enviromental aids, also added a temporary way to fetch player refs for optimization purposes using an interface.  

To make things work, just add the enviromental aids manager to an empty gameobject, and add the player tag to the player.

example scene is called enviromental aids :3

2024-03-20 11:17 UTC, avinash751 approved these changes
code looks gucci, my only suggestion  is for the environmental aids manager to find a way to split this giga function that can become super huge, into small bit sized functions for each reference

2024-03-20 11:19 UTC, devTrivedi1 approved these changes
Like the concept, the only thing I think that needs to be looked at is the whole speed thing cause I guess it's set permanently cause I was ZOOOOOMIN everywhere the second I hit it on the rail xd but yeah other than that looks good for me

2024-03-22 12:39 UTC, HassanAbusalih requested changes

2024-03-22 13:31 UTC, somnolentz commented on Assets/PROJECT/Scripts/Enviromental Objects/EnviromentalAidManager.cs
ok

2024-03-22 19:06 UTC, merged