El cockoracha
devTrivedi1/MajorProject pull request #174
Opened 2024-04-15 19:47 UTC by Armaantakyar1

1. everything viewable in ObsacleTestScene.
2. Works in Build no issues
3. Implemented resetting
Close #60 as complete
The enemies inherits from EnviromentalAid instead from EnemyBase as there is no bullet spawning or Rotations.
The exploding is done through the PhysicsUtilities.KnockbackWithinRadius.

2024-04-16 06:43 UTC, avinash751 approved these changes
Code Looks good to me , functionality wise, it works as intended and i have two suggestions that i think you need to in a later sprint, 

1. is a color pulsation of the material when the countdown for explosion is happening
2. make the vertical boost higher if a perfect stomp is done( if you can do this  today , that would be good, if not you can do later)

2024-04-18 06:20 UTC, devTrivedi1 approved these changes

2024-04-18 06:34 UTC, HassanAbusalih requested changes

2024-04-18 07:06 UTC, HassanAbusalih approved these changes
Gaming

2024-04-18 07:11 UTC, merged